Azmoon/Controllers/AzmoonTestController.cs
using Azmoon.Models;
using Microsoft.AspNetCore.Mvc;

namespace Azmoon.Controllers
{
    public class AzmoonTestController : Controller
    {
        private readonly ApplicationDbContext _db;
        public AzmoonTestController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult AzmoonIndex() => View();

        public IActionResult GetAllDatas()
        {
            var result = _db.TblApplicants.ToList();
            return View(result);
        }
    }
}

Azmoon/Controllers/SecondReportsController.cs
using Aspose.Cells;
using Azmoon.Models;
using Azmoon.Utilities;
using Azmoon.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Azmoon.Controllers
{
    public class SecondReportsController : Controller
    {
        private readonly ApplicationDbContext db;

        public SecondReportsController(ApplicationDbContext _db)
        {
            db = _db;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult ReportConfirm(List<string> selectedColumns, string title)
        {
            SecondReportsViewModel viewModel = new SecondReportsViewModel();
            viewModel.Title = title;
            viewModel.selectedColumns.AddRange(selectedColumns);

            return View(viewModel);
        }
        public IActionResult PreReport(SecondReportsViewModel viewModel)
        {

            var workbook = new Workbook();
            var worksheet = workbook.Worksheets[0];

            worksheet.Cells["A2"].PutValue("ID");
            worksheet.Cells["B2"].PutValue("FirstName");
            worksheet.Cells["C2"].PutValue("LastName");
            worksheet.Cells["D2"].PutValue("PostalCode");
            worksheet.Cells["E2"].PutValue("Tel");
            worksheet.Cells["F2"].PutValue("Email");

            worksheet.Cells.Merge(0, 0, 1, 6);
            worksheet.Cells[0, 0].PutValue(viewModel.Title);

            Style style = workbook.CreateStyle();
            style.HorizontalAlignment = TextAlignmentType.Center;
            style.VerticalAlignment = TextAlignmentType.Center;
            style.Font.IsBold = true;
            worksheet.Cells[0, 0].SetStyle(style);

            foreach (var column in viewModel.selectedColumns)
            {
                if (SD.allColumns.Contains(column))
                {
                    switch (column.ToLower())
                    {
                        case "id":
                            var ids = db.TblApplicants1.Select(a => a.Id).ToList();
                            for (int i = 0; i < ids.Count; i++)
                            {
                                worksheet.Cells[$"A{i + 4}"].PutValue(ids[i]);
                            }
                            break;
                        case "firstname":
                            var firstNames = db.TblApplicants1.Select(a => a.FirstName).ToList();
                            for (int i = 0; i < firstNames.Count; i++)
                            {
                                worksheet.Cells[$"B{i + 4}"].PutValue(firstNames[i]);
                            }
                            break;
                        case "lastname":
                            var lastNames = db.TblApplicants1.Select(a => a.LastName).ToList();
                            for (int i = 0; i < lastNames.Count; i++)
                            {
                                worksheet.Cells[$"C{i + 4}"].PutValue(lastNames[i]);
                            }
                            break;
                        case "postalcode":
                            var postalCodes = db.TblApplicants1.Select(a => a.PostalCode).ToList();
                            for (int i = 0; i < postalCodes.Count; i++)
                            {
                                worksheet.Cells[$"D{i + 4}"].PutValue(postalCodes[i]);
                            }
                            break;
                        case "tel":
                            var tels = db.TblApplicants1.Select(a => a.Tel).ToList();
                            for (int i = 0; i < tels.Count; i++)
                            {
                                worksheet.Cells[$"E{i + 4}"].PutValue(tels[i]);
                            }
                            break;
                        case "email":
                            var emails = db.TblApplicants1.Select(a => a.Email).ToList();
                            for (int i = 0; i < emails.Count; i++)
                            {
                                worksheet.Cells[$"F{i + 4}"].PutValue(emails[i]);
                            }
                            break;
                        default:
                            break;
                    }
                }
            }

            var stream = new MemoryStream();
            workbook.Save(stream, SaveFormat.Xlsx);

            // Return the file as a download
            var fileName = "Sample.xlsx";
            var contentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            stream.Position = 0;
            var file = File(stream, contentType, fileName);
            return file;
        }
    }
}

Azmoon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Azmoon</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/Azmoon.styles.css" asp-append-version="true" />
	<link rel="stylesheet" href="//cdn.datatables.net/1.13.4/css/dataTables.dataTables.min.css" />

	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<script src="//cdn.datatables.net/1.13.4/js/dataTables.min.js"></script>
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Azmoon</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="AzmoonTest" asp-action="GetAllDatas">Azmoon</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="SecondReports" asp-action="Index">Azmoon 2</a>

						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2024 - Azmoon - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>


	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>